input_dir: /global/cfs/cdirs/m3443/data/PowerWeek
project: PowerWeek_MetricLearning

data_split: [80, 10, 10]
input_features: 4
emb_hidden: 512
emb_dim: 14
nb_layer: 4
activation: Tanh

knn: 300
radius: 0.1
margin: 0.1

positive_weight: 1.0
warmup: 100
lr: 0.0001
patience: 200
max_epochs: 10
factor: 0.5